### ISSUE TITLE
ImportError: No module named 'html.entities' when trying to install with `pip`

### ISSUE THREAD

**Issue by thoughtcodex** [pricingassistant/mongokat#8]
`pip install git+https://github.com/pricingassistant/mongokat` results in the following error on OS X 10.10.3 ( with and without `sudo` or `beautifulsoup4` installed )

```
Collecting pytest-html==1.0 (from mongokat==0.1.0)
  Downloading pytest-html-1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 3, in <module>
      File "/Users/liam/Developer/hydra/venv_orm/lib/python3.4/site-packages/setuptools/__init__.py", line 11, in <module>
        from setuptools.extension import Extension
      File "/Users/liam/Developer/hydra/venv_orm/lib/python3.4/site-packages/setuptools/extension.py", line 8, in <module>
        from .dist import _get_unpatched
      File "/Users/liam/Developer/hydra/venv_orm/lib/python3.4/site-packages/setuptools/dist.py", line 16, in <module>
        from setuptools.depends import Require
      File "/Users/liam/Developer/hydra/venv_orm/lib/python3.4/site-packages/setuptools/depends.py", line 6, in <module>
        from setuptools import compat
      File "/Users/liam/Developer/hydra/venv_orm/lib/python3.4/site-packages/setuptools/compat.py", line 44, in <module>
        from html.entities import name2codepoint
    ImportError: No module named 'html.entities'

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-ux57xps8/pytest-html
```

**Comment by sylvinus** [comment]
Hi! This is a Python 3 issue, for which we don't have support yet, see #5. Would gladly accept patches for it though...

For this particular error, the `pytest-html` dependency is clearly optional for mongokat, but that will probably not be the only issue.

Let's continue at #5
